stages:
  - latest
  - next
  - name: release
    if: branch = master
  - name: publish
    if: branch = master

language: node_js

node_js:
  - "10"

jobs:
  include:
    - stage: latest
      on:
        tags: false
      cache: npm
      script: node ./src/index.js latest
    - stage: next
      on:
        tags: false
      cache: npm
      script: node ./src/index.js next
    - stage: release
      on:
        tags: false
      cache: npm
      script: node ./src/index.js release
    - stage: publish
      on:
        tags: false
      cache: npm
      script: node ./src/index.js update
      deploy:
        skip_cleanup: true
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN